### ISSUE TITLE
When do you intend to release version 1.0?

### ISSUE THREAD

**Issue by gulima** [ultraq/thymeleafjs#18]
I'm very interested in it.

I'm new to this area, and I feel bad that there's no a natural template engine for javascript. Certainly I would promote the adoption of thymeleafjs in my organization, but not in "beta".

Thank you and congratulations for the work!

**Comment by ultraq** [comment]
Glad to hear your enthusiasm for the project @gulima 😃  However, a "1.0" release is still very far away, maybe not until next year given my current pace and all the things I want to accomplish for a good experience between this and the original Thymeleaf (all added as issues to this repo, and some of which I'm still exploring how best to do), before I'm comfortable removing the beta/in-development tag.
