### ISSUE TITLE
It is not possible to escape literal with single quotes

### ISSUE THREAD

**Issue by rpresb** [ultraq/thymeleafjs#23]
It is not possible to escape literal with single quotes in th:text

Example:

th:text="'I can''t do this'" or th:text="'I can\'t do this'"

**Comment by ultraq** [comment]
I've just uploaded a 0.17.2 version which added support for escaping single quotes by using the backslash `\` character as that seems to the be the escape mechanism described in the original Thymeleaf docs: https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#text-literals
