### ISSUE TITLE
ReplaceAttributeProcessor

### ISSUE THREAD

**Issue by radudalbea** [ultraq/thymeleafjs#24]
Hi,

Could you please add also a replace fragment processor. I can do a pull request if you want.

Thanks

**Comment by ultraq** [comment]
I'll have a go at this, try to get something out within the week 🙂

**Comment by ultraq** [comment]
I've just published 0.14.0 with a basic replace fragment processor.  Works for a very basic replacement, but I haven't created a bunch of tests around it yet.  If there are any issues with it feel free to raise another issue.
