### ISSUE TITLE
typescript version is not available

### ISSUE THREAD

**Issue by VarunJohar** [ultraq/thymeleafjs#37]
Able to use it using require keyword but getting error in using as import

Error Details :-   '@types/thymeleaf@latest' is not in the npm registry.

**Comment by ultraq** [comment]
thymeleafjs doesn't publish any type information - I don't use TypeScript so am not very good with that.  From what I understand though, the @types/* packages are a community effort, which can be added to by reading the instructions on https://github.com/DefinitelyTyped/DefinitelyTyped and making a PR there.  So if you're interested in having types for thymeleafjs you could add it there.

Maybe one day this module will publish its own type definitions, but given the API is still being changed quite a lot in these 0.x versions and my inexperience with TypeScript, I'm not too keen on including them in this project at the moment.
