### ISSUE TITLE
Literal Substitution not working

### ISSUE THREAD

**Issue by rahuldjoshi28** [ultraq/thymeleafjs#42]
Hello,
I tried to parse template, `|How are you ${name}?|` but its throwing error `Failed to parse`
I checked source code but couldn't find matching rule for parsing Literal Substition. 
But in documentation (https://github.com/ultraq/thymeleafjs/issues/20) its mentioned that it is supported

**Comment by ultraq** [comment]
No, literal substitutions aren't supported yet, and the entry for it in #20 is currently unticked, which is the one that looks like this:

> ### Text operations
> 
>  - [x] String concatenation: `+`
>  - [ ] Literal substitutions: `|The name is ${name}|`
