### ISSUE TITLE
IfThenElseCondition can't parse empty string outputs 

### ISSUE THREAD

**Issue by abousta** [ultraq/thymeleafjs#46]
Hi,

As it is my first report, I would like to thank you first for this very well coded and helpful project.

The expression processor seems to fail parsing a ternary condition that could output an empty string.

Steps to reproduce this bug : 
- In test/standard/expressions/ThymeleafExpressionLanguage.js, run the test IfThenElseCondition / Executes the true branch 
--> success
- Change the test expression from `${condition} ? 'Hello!' : 'Goodbye :('` to `${condition} ? '' : 'Goodbye :('  `
--> Error: Failed to parse "${condition} ? '' : 'Goodbye :('"
- Or change the test expression from `${condition} ? 'Hello!' : 'Goodbye :('` to `${condition} ? 'Hello!' : ''` 
--> Error: Failed to parse "${condition} ? 'Hello!' : ''"

**Comment by ultraq** [comment]
Hi there, thanks for the bug report!  I've reproduced the error with the steps you've provided (thank you for those steps too!), and was able to track the problem down to the 'string literals' rule:

https://github.com/ultraq/thymeleafjs/blob/8523a3545bc1e1a7fc94c348c1fbb2ba35da9833/source/standard/expressions/ThymeleafExpressionLanguage.js#L259-L266

Looks like I'm attempting to do some regex trick which won't work with empty strings.  I'll have to figure out what I'm trying to do there and see how to make it work with empty strings 🤔

**Comment by abousta** [comment]
Maybe you could try `'^$|.*?(?!\\').'`

That would mean something like 
- You should be between two quotes
- Inside those quotes, you could have an empty string OR _the previous regex you coded, ie .*?(?!\\')._

**Comment by abousta** [comment]
Sorry... I wrote too soon. My previous regex doesn't fail if you miss the first or last quote (I hate regex :)) )

But I think this one should work: `''|'.*?(?!\\').'` , don't you ?

**Comment by ultraq** [comment]
I tried a few other things, but the fix ended up being pretty much what you've suggested, so thank you for that 👍  I'll push a release out with this fix in it soon.
